# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_mainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_mainWindow(object):
    def setupUi(self, mainWindow):
        mainWindow.setObjectName("mainWindow")
        mainWindow.setEnabled(True)
        mainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(mainWindow)
        self.centralwidget.setEnabled(True)
        self.centralwidget.setObjectName("centralwidget")
        self.read_emm_button = QtWidgets.QPushButton(self.centralwidget)
        self.read_emm_button.setGeometry(QtCore.QRect(40, 30, 131, 51))
        self.read_emm_button.setObjectName("read_emm_button")
        self.result_label = QtWidgets.QLabel(self.centralwidget)
        self.result_label.setGeometry(QtCore.QRect(20, 230, 121, 21))
        self.result_label.setObjectName("result_label")
        self.not_classify_label = QtWidgets.QLabel(self.centralwidget)
        self.not_classify_label.setGeometry(QtCore.QRect(20, 340, 281, 16))
        self.not_classify_label.setObjectName("not_classify_label")
        self.detailed_results_button = QtWidgets.QPushButton(self.centralwidget)
        self.detailed_results_button.setGeometry(QtCore.QRect(640, 300, 141, 28))
        self.detailed_results_button.setObjectName("detailed_results_button")
        self.help_label = QtWidgets.QLabel(self.centralwidget)
        self.help_label.setGeometry(QtCore.QRect(210, 10, 571, 181))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.help_label.sizePolicy().hasHeightForWidth())
        self.help_label.setSizePolicy(sizePolicy)
        self.help_label.setObjectName("help_label")
        self.result_browser = QtWidgets.QTextBrowser(self.centralwidget)
        self.result_browser.setGeometry(QtCore.QRect(20, 260, 601, 61))
        self.result_browser.setObjectName("result_browser")
        self.copy_button = QtWidgets.QPushButton(self.centralwidget)
        self.copy_button.setGeometry(QtCore.QRect(640, 260, 141, 28))
        self.copy_button.setObjectName("copy_button")
        self.not_handle_browser = QtWidgets.QTextBrowser(self.centralwidget)
        self.not_handle_browser.setGeometry(QtCore.QRect(20, 370, 601, 201))
        self.not_handle_browser.setObjectName("not_handle_browser")
        self.emm_name_label = QtWidgets.QLabel(self.centralwidget)
        self.emm_name_label.setGeometry(QtCore.QRect(20, 180, 71, 41))
        self.emm_name_label.setObjectName("emm_name_label")
        self.add_emm_button = QtWidgets.QPushButton(self.centralwidget)
        self.add_emm_button.setGeometry(QtCore.QRect(40, 100, 131, 51))
        self.add_emm_button.setObjectName("add_emm_button")
        self.emm_filename_browser = QtWidgets.QTextBrowser(self.centralwidget)
        self.emm_filename_browser.setGeometry(QtCore.QRect(100, 180, 521, 41))
        self.emm_filename_browser.setObjectName("emm_filename_browser")
        self.copy_detailed_results_button = QtWidgets.QPushButton(self.centralwidget)
        self.copy_detailed_results_button.setGeometry(QtCore.QRect(640, 340, 141, 51))
        self.copy_detailed_results_button.setObjectName("copy_detailed_results_button")
        mainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(mainWindow)
        self.statusbar.setObjectName("statusbar")
        mainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(mainWindow)
        self.read_emm_button.clicked.connect(mainWindow.read_emm_files) # type: ignore
        self.copy_button.clicked.connect(mainWindow.copy_event) # type: ignore
        self.detailed_results_button.clicked.connect(mainWindow.print_detailed_info) # type: ignore
        self.add_emm_button.clicked.connect(mainWindow.add_emm_files) # type: ignore
        self.copy_detailed_results_button.clicked.connect(mainWindow.copy_details_event) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(mainWindow)

    def retranslateUi(self, mainWindow):
        _translate = QtCore.QCoreApplication.translate
        mainWindow.setWindowTitle(_translate("mainWindow", "自动生成mme借物列表："))
        self.read_emm_button.setText(_translate("mainWindow", "读取emm文件"))
        self.result_label.setText(_translate("mainWindow", "生成结果:"))
        self.not_classify_label.setText(_translate("mainWindow", "未识别的mme/场景/模型，请检查一下:"))
        self.detailed_results_button.setText(_translate("mainWindow", "详细信息"))
        self.help_label.setText(_translate("mainWindow", "<html><head/><body><p>使用说明</p><p>1.←读入.emm文件，注意是.emm不是.pmm</p><p>2.下方出现生成结果，如有错误请在右边详细信息窗口修改</p><p>3.在生成过程中发现未登记的mme会弹出窗口，请编辑信息后选择是否录入</p><p>程序会把模型和场景文件一起识别，请自行选择忽略</p></body></html>"))
        self.copy_button.setText(_translate("mainWindow", "复制到剪贴板"))
        self.emm_name_label.setText(_translate("mainWindow", "读取文件:"))
        self.add_emm_button.setText(_translate("mainWindow", "追加emm文件"))
        self.copy_detailed_results_button.setText(_translate("mainWindow", "复制mme名列表\n"
"到剪贴板"))
